services:
  backend:
    container_name: 'kupipodariday-backend'
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend-compose-kupipodariday
    restart: always
    ports:
      - '3001:3001'
    env_file: .env
    networks:
      - internal

  frontend:
    container_name: 'kupipodariday-frontend'
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend-compose-kupipodariday
    env_file: .env
    restart: always
    ports:
      - '8080:80'
    networks:
      - external

  postgres:
    container_name: 'postgres'
    image: postgres:alpine
    env_file: .env
    restart: always
    volumes:
      - pg_data:/data/postrgres
    networks:
      - internal

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - internal

volumes:
  pg_data:

networks:
  internal:
  external: